/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distributed.computing;

import distributed.computing.appender.JTextAreaAppender;
import distributed.computing.bootstrap.Bootstrap;
import distributed.computing.bootstrap.BootstrapShutdownHook;
import distributed.computing.bootstrap.response.RegResponse;
import distributed.computing.config.BootstrapServerConfig;
import distributed.computing.config.NodeContext;
import distributed.computing.domain.model.FileManager;
import distributed.computing.domain.model.PeerNode;
import distributed.computing.listner.Listener;
import distributed.computing.listner.UdpListener;
import distributed.computing.messaging.broadcast.MessageCache;
import distributed.computing.util.PeerNodeObserver;
import distributed.computing.util.SearchUtil;
import distributed.computing.util.Utils;
import java.awt.Color;
import java.io.*;
import javax.swing.JOptionPane;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.ListModel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author yasitham
 */
public class PeerForm extends javax.swing.JFrame implements PeerNodeObserver{

    private static final Logger LOGGER = LogManager.getLogger(PeerForm.class.getName());


    private static DefaultListModel resultListModel = new DefaultListModel<String>();
    
    /**
     * Creates new form PeerForm
     */
    public PeerForm() {
        initComponents();
        JTextAreaAppender.addTextArea(this.logTxtArea);
        txtNodeIp.setText(Utils.getIP());
        NodeContext.tellMeWhenChildChanged(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NodeName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bsIP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNodeIp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bsPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NodePort = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        bsRegButton = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        keyWord = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        spTtl = new javax.swing.JSpinner();
        searchButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        peerName1 = new javax.swing.JLabel();
        peerName2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultList = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLocalFileNames = new javax.swing.JTextArea();
        addFileNamesBtn = new javax.swing.JButton();
        btnComments = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        logTxtArea = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peer Properties");
        setName("PeerConfig"); // NOI18N

        jLabel4.setText("Node Name:");

        jLabel1.setText("BS IP:");

        bsIP.setEnabled(false);
        bsIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsIPActionPerformed(evt);
            }
        });

        jLabel11.setText("Node IP:");

        jLabel2.setText("BS Port:");

        bsPort.setEnabled(false);

        jLabel3.setText("Node Port:");

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        bsRegButton.setText("Register");
        bsRegButton.setEnabled(false);
        bsRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsRegButtonActionPerformed(evt);
            }
        });

        lblStatus.setBackground(new java.awt.Color(158, 158, 158));
        lblStatus.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(101, 101, 101));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("OFFLINE");
        lblStatus.setFocusable(false);
        lblStatus.setOpaque(true);

        jLabel7.setText("Key Word:");

        keyWord.setEnabled(false);

        jLabel12.setText("TTL");

        spTtl.setModel(new javax.swing.SpinnerNumberModel(10, 0, null, 1));

        searchButton.setText("Search");
        searchButton.setEnabled(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NodeName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsIP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spTtl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsPort, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNodeIp, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(NodePort, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(keyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {NodeName, bsIP, keyWord});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bsRegButton, searchButton});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {applyButton, lblStatus});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(NodeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtNodeIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(NodePort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(bsIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(bsPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsRegButton)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchButton)
                    .addComponent(spTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(keyWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1))
        );

        jLabel8.setText("Result:");

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Peer 1:");

        jLabel6.setText("Peer 2:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peerName1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {peerName1, peerName2});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel5, jLabel6});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(peerName1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, jLabel6, peerName1, peerName2});

        resultList.setModel(resultListModel);
        resultList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                resultListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(resultList);

        jLabel9.setText("File names");

        jButton1.setText("Clear files");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtLocalFileNames.setEditable(false);
        txtLocalFileNames.setColumns(20);
        txtLocalFileNames.setRows(5);
        txtLocalFileNames.setText("Adventures of Tintin\nJack and Jill\nGlee\nThe Vampire Diarie\nKing Arthur\nWindows XP\nHarry Potter\nKung Fu Panda\nLady Gaga\nTwilight\nWindows 8\nMission Impossible\nTurn Up The Music\nSuper Mario\nAmerican Pickers\nMicrosoft Office 2010\nHappy Feet\nModern Family\nAmerican Idol\nHacking for Dummies");
        txtLocalFileNames.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtLocalFileNamesCaretUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(txtLocalFileNames);

        addFileNamesBtn.setText("Add File Names");
        addFileNamesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileNamesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(addFileNamesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel9)
                    .addComponent(addFileNamesBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnComments.setText("forum");
        btnComments.setEnabled(false);
        btnComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComments, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComments))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Log");

        logTxtArea.setEditable(false);
        logTxtArea.setBackground(new java.awt.Color(1, 1, 1));
        logTxtArea.setColumns(20);
        logTxtArea.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        logTxtArea.setForeground(new java.awt.Color(82, 181, 97));
        logTxtArea.setRows(5);
        logTxtArea.setLineWrap(true);
        logTxtArea.setWrapStyleWord(true);
        logTxtArea.setEditable (false);
        jScrollPane3.setViewportView(logTxtArea);
        jScrollPane3.setVisible(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bsIPActionPerformed

    private void bsRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsRegButtonActionPerformed
        String bsIpStr = bsIP.getText();
        String bsPortStr = bsPort.getText();
        
        boolean valid = true;
        if (bsIpStr.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Bootstrap IP cannot be empty");
            valid = false;
        }
        
        if (bsPortStr.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Bootstrap Port cannot be empty");
            valid = false;
        }
         
        try{
           int intBsPort = Integer.parseInt(bsPortStr);
           if (!(intBsPort >= 1024 && intBsPort <= 65535)) {
                JOptionPane.showMessageDialog(rootPane, "Bootstrap Port should be a valid port number (1024 - 65535)");
                valid = false;
           }
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Bootstrap Port should be a valid port number (1024 - 65535)");
            valid = false;
        }
        
        if (valid) {
            BootstrapServerConfig.setHost(bsIP.getText());
            BootstrapServerConfig.setPort(Integer.parseInt(bsPort.getText()));
            LOGGER.info("BS IP: " + bsIP.getText() + ", BS Port: " +  bsPort.getText());

            Listener udpListener = UdpListener.getInstance();
            udpListener.initListener(NodeContext.getPort());

            if (!NodeContext.isOnline()) {
                //if offline

                RegResponse regResponse = null;
                try {
                    regResponse = Bootstrap.register();
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(rootPane, "Registration failed!, " + e.getMessage());
                }
                if(regResponse.isRegOk()) {
//                    bsRegButton.setText("Unregister");
                    bsRegButton.setEnabled(false);
                    NodeContext.setOnline(true);
                    lblStatus.setText("ONLINE");
                    lblStatus.setForeground(Color.GREEN);
                    lblStatus.setBackground(new Color(91, 128, 92));
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Registration failed!, " + regResponse.getStatusMessage());
                }
            } else {
                //if online
                if(Bootstrap.unregister()) {
                    bsRegButton.setText("Register");
                    NodeContext.setOnline(false);
                    lblStatus.setText("OFFLINE");
                    lblStatus.setForeground(Color.GRAY);
                    lblStatus.setBackground(Color.LIGHT_GRAY);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Failed to unregister");
                }
            }
            
            Runtime.getRuntime().addShutdownHook(new BootstrapShutdownHook());
            MessageCache.initCachingScheduler();//init caching scheduler
            
            keyWord.setEnabled(true);
            searchButton.setEnabled(true);
            txtLocalFileNames.setEnabled(true);
            txtLocalFileNames.setEditable(valid);
            NodeContext.setIp(txtNodeIp.getText());
            
            
        }
        
        
    }//GEN-LAST:event_bsRegButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        String nodePortStr = NodePort.getText();
        String nodeNameStr = NodeName.getText();
        
        boolean valid = true;
        if (nodeNameStr.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Node name cannot be empty");
            valid = false;
        }
        
        if (nodeNameStr.contains(" ")){
            JOptionPane.showMessageDialog(rootPane, "Node name should be a single word");
            valid = false;
        }
        
        if (nodePortStr.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Node port cannot be empty");
            valid = false;
        }
        
        try{
           int intPort = Integer.parseInt(nodePortStr);
           if (!(intPort >= 1024 && intPort <= 65535)) {
                JOptionPane.showMessageDialog(rootPane, "Node port should be a valid port number (1024 - 65535)");
                valid = false;
           }
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Node port should be a valid port number (1024 - 65535)");
            valid = false;
        }
        if (valid) {
            NodeContext.setIp(txtNodeIp.getText());
            NodeContext.setPort(Integer.parseInt(NodePort.getText()));
            NodeContext.setUserName(NodeName.getText()); 
            LOGGER.info("Node Name: "+ NodeName.getText() + ", Node IP: "+  Utils.getIP()+", Node Port:"+ NodePort.getText());
            bsIP.setEnabled(true);
            bsPort.setEnabled(true);
            bsRegButton.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_applyButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        resultListModel.clear();
        SearchUtil.search(keyWord.getText(), (int) spTtl.getValue());        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void txtLocalFileNamesCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtLocalFileNamesCaretUpdate
        fileNamesUpdate();
    }//GEN-LAST:event_txtLocalFileNamesCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtLocalFileNames.setText("");
        FileManager.clear();
        LOGGER.debug("cear files");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        resultListModel.clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resultListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resultListValueChanged
 
        if (!resultList.isSelectionEmpty()) {
            btnComments.setEnabled(true);
        } else {
            btnComments.setEnabled(false);
        }
        
    }//GEN-LAST:event_resultListValueChanged

    private void btnCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentsActionPerformed
        if (!resultList.isSelectionEmpty()) {
            resultList.getSelectedValue();
            new Forum().setVisible(true);
        }
    }//GEN-LAST:event_btnCommentsActionPerformed

    private void addFileNamesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileNamesBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("Tex files", "txt", "TXT");
        fileChooser.setFileFilter(filter);
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txtLocalFileNames.setText(new String());            
            File file = fileChooser.getSelectedFile();
            String filenames = "";
            try {
                BufferedReader br = new BufferedReader(new FileReader(file));
                while(br.ready()){
                    String line = br.readLine();
                    if (!filenames.isEmpty()) {
                        filenames = filenames + "\n";
                    }
                    filenames = filenames + line;
                }
                txtLocalFileNames.setText(filenames);
            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(null, "File not found");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Couldn't read file");
            }

        }        
    }//GEN-LAST:event_addFileNamesBtnActionPerformed
   
    public static void addSearchResult(String fileName, String location) {
        synchronized(resultListModel) {
            resultListModel.addElement(location + " : " + fileName);
        }        
    }
    
    public static void clearSearchResult() {
        synchronized(resultListModel) {
            resultListModel.clear();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NodeName;
    private javax.swing.JTextField NodePort;
    private javax.swing.JButton addFileNamesBtn;
    private javax.swing.JButton applyButton;
    private javax.swing.JTextField bsIP;
    private javax.swing.JTextField bsPort;
    private javax.swing.JButton bsRegButton;
    private javax.swing.JButton btnComments;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField keyWord;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextArea logTxtArea;
    private javax.swing.JLabel peerName1;
    private javax.swing.JLabel peerName2;
    private static javax.swing.JList<String> resultList;
    private javax.swing.JButton searchButton;
    private javax.swing.JSpinner spTtl;
    private javax.swing.JTextArea txtLocalFileNames;
    private javax.swing.JTextField txtNodeIp;
    // End of variables declaration//GEN-END:variables


    public void fileNamesUpdate() {
        
        String fileNames = txtLocalFileNames.getText();
        if (!fileNames.isEmpty()) {
            FileManager.clear();
            if (fileNames.trim().contains("\n")) {
                String fileNamesArr[] = fileNames.split("\n");
                for(String fileName : fileNamesArr) {
                    FileManager.addFile(fileName);
                    LOGGER.debug("local file: {}", fileName.trim());
                }
            } else {
                FileManager.addFile(fileNames);
                LOGGER.debug("local file: {}", fileNames.trim());
            }
            LOGGER.debug("Files updated");
        }
        
    }

    @Override
    public void onChildChanged(List<PeerNode> children) {
        if (children.isEmpty()) {
            peerName1.setText("");
            peerName2.setText("");
        }
        int i = 0;
        for (PeerNode node : NodeContext.getChildren()) {
            if (i == 0)
                peerName1.setText(node.getUsername());
            else if (i == 1) {
                peerName2.setText(node.getUsername());
            }
            i++;
        }
    }
}
